management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh

message-name: check-me

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
