management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh

server:
  port: 8092

message-name: check-test

spring:
  bus:
    destination: my-test-queue-for-refresh
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

zeebe:
  client:
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true
